### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by xqtzal** [Sookhaal/auri#3]
Hello, I'm having trouble with the installation. I don't know what's happening but the traceback says
 " File "<maya console>", line 2, in <module>
#   File "C:/Users//Documents/maya/2020/scripts\auri\app.py", line 39, in bootstrap
#     bootstrap_maya()
#   File "C:/Users//Documents/maya/2020/scripts\auri\app.py", line 17, in bootstrap_maya
#     win = BootstrapView(parent=pmc.toQtObject("MayaWindow"), statusbar=False)
#   File "C:/Users//Documents/maya/2020/scripts\auri\views\bootstrap_view.py", line 20, in __init__
#     self.main_model = MainModel()
#   File "C:/Users//Documents/maya/2020/scripts\auri\models\main_model.py", line 6, in __init__
#     self.categories_model = QtCore.QStringListModel()
# AttributeError: 'module' object has no attribute 'QStringListModel' #"
I don't know how to fix this, can you help me?

**Comment by Sookhaal** [comment]
Hello, I'm having a look, it's been a while since I've used it though, not sure if it works on new version of Maya :/ I'll keep you updated.

**Comment by Sookhaal** [comment]
An update to Qt.py was required (it's been 3 years now).
e9f4edbd67901df4c8892edef9ebb1a2f83e7968 should fix the issue.

I do not advise you to use Auri in a production environment as is, it is quite old now, and is in need of a complete rewrite.
Although It should work, I will not provide support for the rigging modules, especially for newer versions of maya 😄.

The UI is working on Maya 2020 now at least 😃!
